main:
  - identifier: "home"
    pageRef: "/"
    weight: 1

  - identifier: "about"
    pageRef: "about"
    weight: 2

  - identifier: "project"
    identifier: "project"
    pageRef: "project"
    weight: 3

  - identifier: "resume"
    url: "/uploads/resume.pdf"
    weight: 4

  - identifier: "contact"
    url: "/about/#contact"
    weight: 5

  # Children under 'project'
  - identifier: "p-cartoon"
    pageRef: "project/cartoon"
    parent: "project"
    weight: 31

  - identifier: "p-cosmetics"
    pageRef: "project/cosmetics"
    parent: "project"
    weight: 32

  - identifier: "p-reco"
    pageRef: "project/recommendation"
    parent: "project"
    weight: 33
