main:
- name: 홈
  url: /
  weight: 1
- name: 자기소개
  url: /about/
  weight: 2
- name: 프로젝트
  url: /project/
  weight: 3
- name: 이력서
  url: /uploads/resume.pdf
  weight: 4
- name: 연락하기
  url: /about/#contact
  weight: 5
