main:
  - identifier: "home"
    name: "홈"
  - identifier: "about"
    name: "자기소개"
  - identifier: "project"
    name: "프로젝트"
  - identifier: "resume"
    name: "이력서"
  - identifier: "contact"
    name: "연락하기"

  - identifier: "p-cartoon"
    name: "AI 캐릭터"
  - identifier: "p-cosmetics"
    name: "화장품 추천"
  - identifier: "p-reco"
    name: "콘텐츠 추천"