main:
  - identifier: "home"
    name: "Home"
  - identifier: "about"
    name: "About"
  - identifier: "project"
    name: "Projects"
  - identifier: "resume"
    name: "Resume"
  - identifier: "contact"
    name: "Contact"

  - identifier: "p-cartoon"
    name: "AI Cartoon"
  - identifier: "p-cosmetics"
    name: "Cosmetics Recommender"
  - identifier: "p-reco"
    name: "Content Recommender"
